#!/usr/bin/env bash

# Copyright (C) 2022 Henrik A. Christensen
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

INSTALL_PATH="$HOME/.local/bin"

if [[ :$PATH == *:"$INSTALL_PATH":* ]]; then
	if [ ! -d $INSTALL_PATH ]; then
		mkdir -p $INSTALL_PATH
		echo "created $INSTALL_PATH"
	fi

	cp bookmark "$INSTALL_PATH/bm" && cd $INSTALL_PATH
	chmod 755 bm
	chmod +x bm
	echo "bookmark was successfully installed!"
else
	echo "$INSTALL_PATH is not in \$PATH"
fi
